spring:
  datasource:
    url: jdbc:postgresql://db:5432/schedule_db
    username: root
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  application:
    name: ScheduleManagementService
